### ISSUE TITLE
Don't forget to include GameSpyOpen

### ISSUE THREAD

**Issue by BinToss** [yumiris/OpenSauce#29]
As suggested by Guardian2433

Or rip it out and replace it with [RetroSpy](https://github.com/GameProgressive/RetroSpyServer)

**Comment by VoidsShadow** [comment]
Uhm...Include, but don't track it. 
Add it to the Ignore list.
Put it in a separate repository.
For convenience, track it as a submodule.

**Comment by BinToss** [comment]
More or less resolved by moving its code to a separate branch.
Refer to #45 for further info.
